# Generated by Django 4.1.5 on 2023-01-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Edad', models.PositiveIntegerField()),
                ('Profesion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
