# Generated by Django 4.1.5 on 2023-01-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='Identificacion',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
