# Generated by Django 4.1.5 on 2023-01-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField()),
                ('profesion', models.IntegerField(choices=[(1, 'Indeterminado'), (2, 'Desempleado'), (3, 'Empleado'), (4, 'Pensionado')])),
            ],
        ),
    ]
